### ISSUE TITLE
Error in data loading

### ISSUE THREAD

**Issue by LuisaMaerz** [Yinghao-Li/CHMM-ALT#1]
Hi there, 

if I try to execude your code (e.g. with the data from Laptop Review) I get the following error:

```
span_dict[(span[0], span[1])] = span[2]
IndexError: string index out of range
```

There seems to be some logic broken in this lines from dataset.py

```
# get true labels
lbs = span_to_label(span_list_to_dict(data['label']), sent_tks)
lbs_list.append(lbs)
# get lf annotations (weak labels) in one-hot format tensor
w_lbs = [span_to_label(span_list_to_dict(data['weak_labels'][lf_idx]), sent_tks) for lf_idx in lf_rec_ids]
```

It tries to parses spans here, but in fact, there are no spans, but single labels.
Maybe I am also mistaken - could you elaborate on this and provide some help?

Thank you

**Comment by Yinghao-Li** [comment]
Hi,

I'm sorry for not getting back to you earlier. From your description, I assume the `dataset.py` you mentioned is from the package `seqlbtoolkit`? If so, can you verify its version is `0.0.2`? I have updated `seqlbtoolkit` but have not updated this repo accordingly. So the new version may not be entirely compatible.

**Comment by Yinghao-Li** [comment]
Turns out I forgot to update the format of the constructed dataset. Fixed it.
